import = [
    "~/.config/alacritty/themes/github_dark_high_contrast.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "regular" }
size = 12

[window]
decorations = "none"

[window.padding]
x = 7
y = 0