import = ["~/.config/alacritty/themes/carbonfox.toml"]
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

[window]
decorations = "none"

[window.padding]
x = 7
y = 0
