import = ["~/.config/alacritty/themes/carbonfox.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
