import = ["~/.config/alacritty/themes/github_dark_high_contrast.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16

[window]
decorations = "none"

[window.padding]
x = 7
y = 0

